"""
Environment variables.
"""
# Cosmos DB for conversation history
COSMOS_ENDPOINT = "COSMOS_ENDPOINT"
COSMOS_KEY = "COSMOS_KEY"
CONTAINER = "CONTAINER"
DATABASE = "DATABASE"
# Chat model
CHAT_MODEL = "CHAT_MODEL"
OPEN_AI_KEY = "OPEN_AI_KEY"
OPEN_AI_ENDPOINT = "OPEN_AI_ENDPOINT"
# RAG search engine
INDEX_NAME = "INDEX_NAME"
SEARCH_KEY = "SEARCH_KEY"
EMBEDDING_MODEL = "EMBEDDING_MODEL"
SEARCH_ENDPOINT = "SEARCH_ENDPOINT"

# Weather agent
AI_PROJ_ENDPOINT = "AI_PROJ_ENDPOINT"
WEATHER_AGENT_ID = "WEATHER_AGENT_ID"
